version: '3'
services:
  anfora:
    build: .
    volumes:
      - ./anfora.yaml:/opt/anfora/src/config/docker-compose.yaml
      - /var/anfora:/var/anfora
    depends_on:
      - db
      - redis

  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: anforapostgres

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/anfora.conf
      - /var/anfora:/var/anfora
    depends_on:
      - anfora

