version: '3'
services:
  anfora:
    build: .
    volumes:
      - ./anfora.yaml:/opt/anfora/src/config/docker-compose.yaml
      - /var/anfora:/var/anfora
    environment:
      REDIS_HOST: redis
      VUE_APP_CLIENT_DOMAIN: http://localhost:8080
    depends_on:
      - db
      - redis

  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: anforapostgres

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/anfora:/var/anfora
    ports:
      - "8080:80"
    depends_on:
      - anfora

