version: '3'
services:
  anfora:
    build: .
    depends_on:
      - db
      - redis

  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: anforapostgres

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      anfora

